# Generated by Django 4.2.4 on 2023-08-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
    ]
